### ISSUE TITLE
Make a release for this mod

### ISSUE THREAD

**Issue by ghost** [Swanderrr/CCleasitstitle#2]
It is encouraged by the CrossCode mod community for: 

- [x] our sanity

- [x] ease of installation

**Comment by Swanderrr** [comment]
@ac2pic my apologies for being a nuisance i was away from town for a few days, what files should be released? Only .zip archive of the mod?

**Comment by ghost** [comment]
You are not being a nuisance. I was just trying to say that it is good practice to have a release. I suggest making a `ccmod` file. All a ccmod file is a renamed zip that has `ccmod.json` at the root.

**Comment by Swanderrr** [comment]
Thanks for your guidance, the mod now has a [release](https://github.com/Swanderrr/CCleasitstitle/releases/tag/v1.0.0), but i would be grateful if you could check on it just in case i messed something up

**Comment by ghost** [comment]
Will do.

**Comment by ghost** [comment]
Looks good to me.
